name: Build Mac Catalyst Release

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    timeout-minutes: 180
    outputs:
      new_build_number: ${{ steps.generate_build_number.outputs.build_number }}
      project_version: ${{ steps.determine_marketing_version.outputs.project_version }}
      pkg_output_path: ${{ steps.build_app.outputs.pkg_output_path }}
      latest_commit_message: ${{ steps.get_latest_commit_details.outputs.commit_message }}
      branch_name: ${{ steps.get_latest_commit_details.outputs.branch_name }}
    env:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      MATCH_READONLY: "true"

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures the full Git history is available
      
      - name: Setup Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/CocoaPods
            ios/Pods
            ~/.npm
            node_modules
            vendor/bundle
          key: ${{ runner.os }}-catalyst-${{ hashFiles('**/package-lock.json', '**/Podfile.lock', '**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-catalyst-

      - name: Clear All Caches
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Clearing Xcode DerivedData..."
          rm -rf ~/Library/Developer/Xcode/DerivedData
          echo "Clearing CocoaPods Cache..."
          rm -rf ~/Library/Caches/CocoaPods
          echo "Clearing npm Cache..."
          npm cache clean --force
          echo "Clearing Ruby Gems Cache..."
          rm -rf ~/.gem
          echo "Clearing Bundler Cache..."
          rm -rf ~/.bundle/cache

      - name: Ensure Correct Branch
        if: github.ref != 'refs/heads/master'
        run: |
          if [ -n "${GITHUB_HEAD_REF}" ]; then
            git fetch origin ${GITHUB_HEAD_REF}:${GITHUB_HEAD_REF}
            git checkout ${GITHUB_HEAD_REF}
          else
            git fetch origin ${GITHUB_REF##*/}:${GITHUB_REF##*/}
            git checkout ${GITHUB_REF##*/}
          fi
          echo "Checked out branch: $(git rev-parse --abbrev-ref HEAD)"

      - name: Get Latest Commit Details
        id: get_latest_commit_details
        run: |
          # Check if we are in a detached HEAD state
          if [ "$(git rev-parse --abbrev-ref HEAD)" == "HEAD" ]; then
            CURRENT_BRANCH=$(git show-ref --head -s HEAD | xargs -I {} git branch --contains {} | grep -v "detached" | head -n 1 | sed 's/^[* ]*//')
          else
            CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          fi
          
          LATEST_COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          
          echo "CURRENT_BRANCH=${CURRENT_BRANCH}" >> $GITHUB_ENV
          echo "LATEST_COMMIT_MESSAGE=${LATEST_COMMIT_MESSAGE}" >> $GITHUB_ENV
          echo "branch_name=${CURRENT_BRANCH}" >> $GITHUB_OUTPUT
          echo "commit_message=${LATEST_COMMIT_MESSAGE}" >> $GITHUB_OUTPUT

      - name: Specify Node.js Version
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.6
          bundler-cache: true

      - name: Install Dependencies with Bundler
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3 --quiet

      - name: Install Node Modules
        run: npm install --omit=dev --yes

      - name: Install CocoaPods Dependencies
        run: |
          bundle exec fastlane ios install_pods
          echo "CocoaPods dependencies installed successfully"

      - name: Update WWDR Certificate
        run: bundle exec fastlane ios update_wwdr_certificate

      - name: Generate Build Number Based on Timestamp
        id: generate_build_number
        run: |
          NEW_BUILD_NUMBER=$(date +%s)
          echo "NEW_BUILD_NUMBER=$NEW_BUILD_NUMBER" >> $GITHUB_ENV
          echo "build_number=$NEW_BUILD_NUMBER" >> $GITHUB_OUTPUT

      - name: Set Build Number
        run: bundle exec fastlane ios increment_build_number_lane

      - name: Determine Marketing Version
        id: determine_marketing_version
        run: |
          MARKETING_VERSION=$(grep MARKETING_VERSION BlueWallet.xcodeproj/project.pbxproj | awk -F '= ' '{print $2}' | tr -d ' ;' | head -1)
          echo "PROJECT_VERSION=$MARKETING_VERSION" >> $GITHUB_ENV
          echo "project_version=$MARKETING_VERSION" >> $GITHUB_OUTPUT
        working-directory: ios

      - name: Set Up Git Authentication
        env:
          ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
        run: |
          git config --global credential.helper 'cache --timeout=3600'
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n x-access-token:${ACCESS_TOKEN} | base64)"

      - name: Create Temporary Keychain
        run: bundle exec fastlane ios create_temp_keychain
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: Create App Store Connect API Key JSON
        run: echo '${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}' > ./appstore_api_key.json

      - name: Setup App Store Connect API Key
        run: bundle exec fastlane ios setup_app_store_connect_api_key
        env:
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}

      - name: Setup Mac Catalyst Provisioning Profiles
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          GIT_URL: ${{ secrets.GIT_URL }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
          ITC_TEAM_NAME: ${{ secrets.ITC_TEAM_NAME }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          bundle exec fastlane ios setup_catalyst_provisioning_profiles

      - name: Build Mac Catalyst App
        id: build_app
        run: |
          bundle exec fastlane ios build_catalyst_app
          
          # Ensure PKG path is set for subsequent steps
          if [ -f "./ios/build/pkg_path.txt" ]; then
            PKG_PATH=$(cat ./ios/build/pkg_path.txt)
            echo "PKG_OUTPUT_PATH=$PKG_PATH" >> $GITHUB_ENV
            echo "pkg_output_path=$PKG_PATH" >> $GITHUB_OUTPUT
            echo "Found PKG at: $PKG_PATH"
          else
            echo "Warning: pkg_path.txt not found, trying to locate PKG file manually..."
            PKG_PATH=$(find ./ios -name "*.pkg" | head -n 1)
            if [ -n "$PKG_PATH" ]; then
              echo "PKG_OUTPUT_PATH=$PKG_PATH" >> $GITHUB_ENV
              echo "pkg_output_path=$PKG_PATH" >> $GITHUB_OUTPUT
              echo "Found PKG at: $PKG_PATH"
            else
              echo "Error: No PKG file found"
              exit 1
            fi
          fi

      - name: Upload Build Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: catalyst_build_logs
          path: ./ios/build_logs/
          retention-days: 7

      - name: Verify PKG File Before Upload
        run: |
          echo "Checking PKG file at: $PKG_OUTPUT_PATH"
          if [ -f "$PKG_OUTPUT_PATH" ]; then
            echo "✅ PKG file exists"
            ls -la "$PKG_OUTPUT_PATH"
          else
            echo "❌ PKG file not found at: $PKG_OUTPUT_PATH"
            echo "Current directory contents:"
            find ./ios -name "*.pkg"
            exit 1
          fi
          
      - name: Upload PKG as Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: BlueWallet_MacCatalyst
          path: ${{ env.PKG_OUTPUT_PATH }}
          retention-days: 7

      - name: Delete Temporary Keychain
        if: always()
        run: bundle exec fastlane ios delete_temp_keychain

  notarize-catalyst:
    needs: build
    runs-on: macos-15
    if: github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'catalyst')
    env:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      NEW_BUILD_NUMBER: ${{ needs.build.outputs.new_build_number }}
      PROJECT_VERSION: ${{ needs.build.outputs.project_version }}
      LATEST_COMMIT_MESSAGE: ${{ needs.build.outputs.latest_commit_message }}
      BRANCH_NAME: ${{ needs.build.outputs.branch_name }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.6
          bundler-cache: true

      - name: Install Dependencies with Bundler
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3 --quiet

      - name: Download PKG from Artifact
        uses: actions/download-artifact@v4
        with:
          name: BlueWallet_MacCatalyst
          path: ./

      - name: Create App Store Connect API Key JSON
        run: echo '${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}' > ./appstore_api_key.json

      - name: Set PKG Path Environment Variable
        run: |
          PKG_PATH=$(find ./ -name "*.pkg" | head -n 1)
          echo "PKG_OUTPUT_PATH=$PKG_PATH" >> $GITHUB_ENV

      - name: Verify PKG Path Before Upload
        run: |
          if [ ! -f "$PKG_OUTPUT_PATH" ]; then
            echo "❌ PKG file not found at path: $PKG_OUTPUT_PATH"
            ls -la $(pwd)
            exit 1
          else
            echo "✅ Found PKG at: $PKG_OUTPUT_PATH"
          fi

      - name: Print Environment Variables for Debugging
        run: |
          echo "LATEST_COMMIT_MESSAGE: $LATEST_COMMIT_MESSAGE"
          echo "BRANCH_NAME: $BRANCH_NAME"
          echo "PROJECT_VERSION: $PROJECT_VERSION"
          echo "NEW_BUILD_NUMBER: $NEW_BUILD_NUMBER"
          echo "PKG_OUTPUT_PATH: $PKG_OUTPUT_PATH"

      - name: Notarize Mac Catalyst App
        run: bundle exec fastlane ios notarize_catalyst
        env:
          APP_STORE_CONNECT_API_KEY_PATH: $(pwd)/appstore_api_key.p8
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          GIT_URL: ${{ secrets.GIT_URL }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
          ITC_TEAM_NAME: ${{ secrets.ITC_TEAM_NAME }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}

      - name: Upload Notarized PKG
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: BlueWallet_MacCatalyst_Notarized
          path: ${{ env.PKG_OUTPUT_PATH_NOTARIZED || env.PKG_OUTPUT_PATH }}
          retention-days: 7

      - name: Post PR Comment
        if: success() && github.event_name == 'pull_request'
        uses: actions/github-script@v6
        env:
          BUILD_NUMBER: ${{ needs.build.outputs.new_build_number }}
          PROJECT_VERSION: ${{ needs.build.outputs.project_version }}
          LATEST_COMMIT_MESSAGE: ${{ needs.build.outputs.latest_commit_message }}
        with:
          script: |
            const buildNumber = process.env.BUILD_NUMBER;
            const version = process.env.PROJECT_VERSION;
            const message = `✅ Mac Catalyst build ${version} (${buildNumber}) has been successfully built and notarized. You can download the macOS installer package from the artifacts.`;
            const prNumber = context.payload.pull_request.number;
            const repo = context.repo;
            github.rest.issues.createComment({
              ...repo,
              issue_number: prNumber,
              body: message,
            });
