name: BuildReproducibleApk
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  buildReproducibleApk:
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Specify node version
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Use npm caches
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Use specific Java version for sdkmanager to work
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Install node_modules
        run: npm install --production

      - name: Extract Version Name and Build Number
        id: version_info
        run: |
          VERSION_NAME=$(grep -m1 versionName android/app/build.gradle | awk '{print $2}' | tr -d '"')
          VERSION_CODE=$(grep -m1 versionCode android/app/build.gradle | awk '{print $2}')
          echo "VERSION_NAME=\"$VERSION_NAME\"" >> $GITHUB_ENV
          echo "VERSION_CODE=\"$VERSION_CODE\"" >> $GITHUB_ENV
          echo "Version Name: $VERSION_NAME"
          echo "Version Code: $VERSION_CODE"

      - name: Build Reproducible APK
        run: |
          chmod +x ./scripts/build-release-apk.sh
          ./scripts/build-release-apk.sh reproducible

      - name: List All APK Outputs
        run: ls -Rla ./android/app/build/outputs/apk/

      - name: Calculate APK Hash
        run: |
          REPRODUCIBLE_APK_PATH="./android/app/build/outputs/apk/reproducible/BlueWallet-Reproducible-${{ env.VERSION_NAME }}(${{ env.VERSION_CODE }}).apk"
          if [ -f "$REPRODUCIBLE_APK_PATH" ]; then
            SHA256_HASH=$(shasum -a 256 "$REPRODUCIBLE_APK_PATH" | awk '{print $1}')
            echo "SHA256 Hash: $SHA256_HASH"
            echo "$SHA256_HASH" > "./android/app/build/outputs/apk/reproducible/BlueWallet-Reproducible-${{ env.VERSION_NAME }}(${{ env.VERSION_CODE }}).sha256.txt"
          else
            echo "APK not found: $REPRODUCIBLE_APK_PATH"
            exit 1
          fi

      - name: Upload Reproducible APK
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: BlueWallet-Reproducible-${{ env.VERSION_NAME }}(${{ env.VERSION_CODE }}).apk
          path: ./android/app/build/outputs/apk/reproducible/BlueWallet-Reproducible-${{ env.VERSION_NAME }}(${{ env.VERSION_CODE }}).apk

      - name: Upload APK Hash
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: BlueWallet-Reproducible-${{ env.VERSION_NAME }}(${{ env.VERSION_CODE }}).sha256.txt
          path: ./android/app/build/outputs/apk/reproducible/BlueWallet-Reproducible-${{ env.VERSION_NAME }}(${{ env.VERSION_CODE }}).sha256.txt