name: BuildReleaseApk
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  buildReleaseApk:
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Specify node version
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Use npm caches
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Use specific Java version for sdkmanager to work
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Install node_modules
        run: npm install --production

      - name: Extract Version Name and Build Number
        id: version_info
        run: |
          VERSION_NAME=$(grep -m1 versionName android/app/build.gradle | awk '{print $2}' | tr -d '"')
          VERSION_CODE=$(grep -m1 versionCode android/app/build.gradle | awk '{print $2}')
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "Version Name: $VERSION_NAME"
          echo "Version Code: $VERSION_CODE"

      - name: Build Release APK
        env:
          KEYSTORE_FILE_HEX: ${{ secrets.KEYSTORE_FILE_HEX }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          BUILD_NUMBER: ${{ env.VERSION_CODE }}
        run: |
          chmod +x ./scripts/build-release-apk.sh
          ./scripts/build-release-apk.sh release

      - name: Upload Release APK
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: BlueWallet-${{ env.VERSION_NAME }}(${{ env.VERSION_CODE }}).apk
          path: ./android/app/build/outputs/apk/release/BlueWallet-${{ env.VERSION_NAME }}(${{ env.VERSION_CODE }}).apk